### ISSUE TITLE
Login/Signup Pages

### ISSUE THREAD

**Issue by ricardoprins** [ricardoprins/CFMKids#22]
- [x] Add basic login page
- [x] Add basic signup page
- [ ] Add responsiveness to login page
- [ ] Add responsiveness to signup page
- [ ] Link login page with backend
- [ ] Link signup page with backend
- [ ] Link main screen with login page

**Comment by DereckAn** [comment]
hello I am Dereck

**Comment by ricardoprins** [comment]
Hi Dereck, I'm Dereck too!
